image: ruby:3.2

before_script:
 - apt-get update -qq && apt-get install -y nodejs npm
 - npm install -g yarn
 - yarn install
 - gem install bundler
 - bundle install

pages:
 stage: deploy
 script:
    - yarn run prod
 artifacts:
    paths:
      - public
 only:
    - main
