url: ""
baseurl: ""
title: "دونا"

# Git Repo information
repo_url: "https://framagit.org/dona/website"

# plugins:
#   - "jekyll-postcss"

collections:
  events:
    output: true
    permalink: /events/:path/
  members:
    output: true
    permalink: /members/:path/

defaults:
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
  - scope:
      path: ""
      type: "members"
    values:
      layout: "member"